Traceback (most recent call last):
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test05/../../riesenia/Ajurecekova/mboxer/mail.py", line 78, in read_method
    mes = open('./'+a[1]+'/'+b[1],'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: './yyy/zzz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test05/../../riesenia/Ajurecekova/mboxer/mail.py", line 133, in <module>
    read_method(f)
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test05/../../riesenia/Ajurecekova/mboxer/mail.py", line 79, in read_method
    except error:
NameError: name 'error' is not defined
